/**
 * MiniMax TTS 音色配置（服务端/客户端共享）。
 * 共 81 个音色：中/英双语支持。
 */
export interface MinimaxVoiceOption {
  id: string
  label: string
  lang: 'zh' | 'en' | 'yue'
  gender: 'male' | 'female' | 'neutral'
  ageTag: 'child' | 'youth' | 'adult' | 'middle' | 'senior' | 'neutral'
  mood: string
  description: string
}

export const MINIMAX_TTS_VOICES: MinimaxVoiceOption[] = [
  // =====================
  // 🇨🇳 普通话 · 基础音色（8 个）
  // =====================
  {
    id: 'male-qn-qingse',
    label: '青涩青年',
    lang: 'zh',
    gender: 'male',
    ageTag: 'youth',
    mood: '阳光、稍带稚气',
    description: '阳光、稍带稚气的青年男声',
  },
  {
    id: 'male-qn-jingying',
    label: '精英青年',
    lang: 'zh',
    gender: 'male',
    ageTag: 'adult',
    mood: '沉稳干练、职场精英',
    description: '沉稳干练、职场精英范',
  },
  {
    id: 'male-qn-badao',
    label: '霸道青年',
    lang: 'zh',
    gender: 'male',
    ageTag: 'middle',
    mood: '强势、有压迫感',
    description: '强势、有压迫感、霸道总裁风',
  },
  {
    id: 'male-qn-daxuesheng',
    label: '青年大学生',
    lang: 'zh',
    gender: 'male',
    ageTag: 'youth',
    mood: '清澈干净、青春校园',
    description: '清澈干净、青春校园感',
  },
  {
    id: 'female-shaonv',
    label: '少女',
    lang: 'zh',
    gender: 'female',
    ageTag: 'youth',
    mood: '甜美可爱、青春活泼',
    description: '甜美可爱、青春活泼',
  },
  {
    id: 'female-yujie',
    label: '御姐',
    lang: 'zh',
    gender: 'female',
    ageTag: 'adult',
    mood: '成熟大气、气场全开',
    description: '成熟大气、气场全开',
  },
  {
    id: 'female-chengshu',
    label: '成熟女性',
    lang: 'zh',
    gender: 'female',
    ageTag: 'middle',
    mood: '温婉知性、岁月沉淀',
    description: '温婉知性、岁月沉淀感',
  },
  {
    id: 'female-tianmei',
    label: '甜美女性',
    lang: 'zh',
    gender: 'female',
    ageTag: 'adult',
    mood: '软糯治愈、甜而不腻',
    description: '软糯治愈、甜而不腻',
  },

  // =====================
  // 🇨🇳 普通话 · 基础音色 Beta（8 个）
  // =====================
  {
    id: 'male-qn-qingse-jingpin',
    label: '青涩青年-beta',
    lang: 'zh',
    gender: 'male',
    ageTag: 'youth',
    mood: '阳光、稍带稚气',
    description: '基础版的高品质升级版',
  },
  {
    id: 'male-qn-jingying-jingpin',
    label: '精英青年-beta',
    lang: 'zh',
    gender: 'male',
    ageTag: 'adult',
    mood: '沉稳干练、职场精英',
    description: '基础版的高品质升级版',
  },
  {
    id: 'male-qn-badao-jingpin',
    label: '霸道青年-beta',
    lang: 'zh',
    gender: 'male',
    ageTag: 'middle',
    mood: '强势、有压迫感',
    description: '基础版的高品质升级版',
  },
  {
    id: 'male-qn-daxuesheng-jingpin',
    label: '青年大学生-beta',
    lang: 'zh',
    gender: 'male',
    ageTag: 'youth',
    mood: '清澈干净、青春校园',
    description: '基础版的高品质升级版',
  },
  {
    id: 'female-shaonv-jingpin',
    label: '少女-beta',
    lang: 'zh',
    gender: 'female',
    ageTag: 'youth',
    mood: '甜美可爱、青春活泼',
    description: '基础版的高品质升级版',
  },
  {
    id: 'female-yujie-jingpin',
    label: '御姐-beta',
    lang: 'zh',
    gender: 'female',
    ageTag: 'adult',
    mood: '成熟大气、气场全开',
    description: '基础版的高品质升级版',
  },
  {
    id: 'female-chengshu-jingpin',
    label: '成熟女性-beta',
    lang: 'zh',
    gender: 'female',
    ageTag: 'middle',
    mood: '温婉知性、岁月沉淀',
    description: '基础版的高品质升级版',
  },
  {
    id: 'female-tianmei-jingpin',
    label: '甜美女性-beta',
    lang: 'zh',
    gender: 'female',
    ageTag: 'adult',
    mood: '软糯治愈、甜而不腻',
    description: '基础版的高品质升级版',
  },

  // =====================
  // 🇨🇳 普通话 · 角色音色（14 个）
  // =====================
  {
    id: 'clever_boy',
    label: '聪明男童',
    lang: 'zh',
    gender: 'male',
    ageTag: 'child',
    mood: '机灵、聪明',
    description: '机灵、聪明小孩',
  },
  {
    id: 'cute_boy',
    label: '可爱男童',
    lang: 'zh',
    gender: 'male',
    ageTag: 'child',
    mood: '萌系、可爱',
    description: '萌系小男孩',
  },
  {
    id: 'lovely_girl',
    label: '萌萌女童',
    lang: 'zh',
    gender: 'female',
    ageTag: 'child',
    mood: '软糯、可爱',
    description: '软糯小女孩',
  },
  {
    id: 'cartoon_pig',
    label: '卡通猪小琪',
    lang: 'zh',
    gender: 'female',
    ageTag: 'child',
    mood: '卡通、搞怪可爱',
    description: '卡通猪小妞，搞怪可爱',
  },
  {
    id: 'bingjiao_didi',
    label: '病娇弟弟',
    lang: 'zh',
    gender: 'male',
    ageTag: 'youth',
    mood: '偏执、占有欲强',
    description: '偏执、占有欲强的少年感',
  },
  {
    id: 'junlang_nanyou',
    label: '俊朗男友',
    lang: 'zh',
    gender: 'male',
    ageTag: 'adult',
    mood: '温柔帅气',
    description: '温柔帅气的男友音',
  },
  {
    id: 'chunzhen_xuedi',
    label: '纯真学弟',
    lang: 'zh',
    gender: 'male',
    ageTag: 'youth',
    mood: '单纯青涩、校园少年',
    description: '单纯青涩、校园少年',
  },
  {
    id: 'lengdan_xiongzhang',
    label: '冷淡学长',
    lang: 'zh',
    gender: 'male',
    ageTag: 'adult',
    mood: '高冷疏离、话少气足',
    description: '高冷疏离、话少气足',
  },
  {
    id: 'badao_shaoye',
    label: '霸道少爷',
    lang: 'zh',
    gender: 'male',
    ageTag: 'youth',
    mood: '傲娇富少、张扬自信',
    description: '傲娇富少、张扬自信',
  },
  {
    id: 'tianxin_xiaoling',
    label: '甜心小玲',
    lang: 'zh',
    gender: 'female',
    ageTag: 'youth',
    mood: '甜系少女、元气满满',
    description: '甜系少女、元气满满',
  },
  {
    id: 'qiaopi_mengmei',
    label: '俏皮萌妹',
    lang: 'zh',
    gender: 'female',
    ageTag: 'youth',
    mood: '古灵精怪、可爱调皮',
    description: '古灵精怪、可爱调皮',
  },
  {
    id: 'wumei_yujie',
    label: '妩媚御姐',
    lang: 'zh',
    gender: 'female',
    ageTag: 'adult',
    mood: '性感撩人、成熟风韵',
    description: '性感撩人、成熟风韵',
  },
  {
    id: 'diadia_xuemei',
    label: '嗲嗲学妹',
    lang: 'zh',
    gender: 'female',
    ageTag: 'youth',
    mood: '撒娇奶音、嗲里嗲气',
    description: '撒娇奶音、嗲里嗲气',
  },
  {
    id: 'danya_xuejie',
    label: '淡雅学姐',
    lang: 'zh',
    gender: 'female',
    ageTag: 'adult',
    mood: '清新脱俗、书卷气',
    description: '清新脱俗、书卷气',
  },

  // =====================
  // 🇨🇳 普通话 · 场景/形象音色（29 个）
  // =====================
  {
    id: 'Chinese (Mandarin)_Reliable_Executive',
    label: '沉稳高管',
    lang: 'zh',
    gender: 'male',
    ageTag: 'middle',
    mood: '商务汇报、领导讲话',
    description: '商务汇报、领导讲话标配',
  },
  {
    id: 'Chinese (Mandarin)_News_Anchor',
    label: '新闻女声',
    lang: 'zh',
    gender: 'female',
    ageTag: 'adult',
    mood: '标准播音腔、字正腔圆',
    description: '标准播音腔、字正腔圆',
  },
  {
    id: 'Chinese (Mandarin)_Mature_Woman',
    label: '傲娇御姐',
    lang: 'zh',
    gender: 'female',
    ageTag: 'adult',
    mood: '高贵冷艳、嘴硬心软',
    description: '高贵冷艳、嘴硬心软',
  },
  {
    id: 'Chinese (Mandarin)_Unrestrained_Young_Man',
    label: '不羁青年',
    lang: 'zh',
    gender: 'male',
    ageTag: 'youth',
    mood: '自由洒脱、个性张扬',
    description: '自由洒脱、个性张扬',
  },
  {
    id: 'Arrogant_Miss',
    label: '嚣张小姐',
    lang: 'zh',
    gender: 'female',
    ageTag: 'adult',
    mood: '盛气凌人、傲气逼人',
    description: '盛气凌人、傲气逼人',
  },
  {
    id: 'Robot_Armor',
    label: '机械战甲',
    lang: 'zh',
    gender: 'neutral',
    ageTag: 'neutral',
    mood: '科幻机甲风、合成电子音',
    description: '科幻机甲风、合成电子音',
  },
  {
    id: 'Chinese (Mandarin)_Kind-hearted_Antie',
    label: '热心大婶',
    lang: 'zh',
    gender: 'female',
    ageTag: 'senior',
    mood: '邻家长辈、唠嗑亲切',
    description: '邻家长辈、唠嗑亲切',
  },
  {
    id: 'Chinese (Mandarin)_HK_Flight_Attendant',
    label: '港普空姐',
    lang: 'zh',
    gender: 'female',
    ageTag: 'adult',
    mood: '港式普通话、空中乘务员',
    description: '港式普通话、空中乘务员',
  },
  {
    id: 'Chinese (Mandarin)_Humorous_Elder',
    label: '搞笑大爷',
    lang: 'zh',
    gender: 'male',
    ageTag: 'senior',
    mood: '诙谐幽默、京味大爷',
    description: '诙谐幽默、京味大爷',
  },
  {
    id: 'Chinese (Mandarin)_Gentleman',
    label: '温润男声',
    lang: 'zh',
    gender: 'male',
    ageTag: 'adult',
    mood: '温和如玉、娓娓道来',
    description: '温和如玉、娓娓道来',
  },
  {
    id: 'Chinese (Mandarin)_Warm_Bestie',
    label: '温暖闺蜜',
    lang: 'zh',
    gender: 'female',
    ageTag: 'adult',
    mood: '陪伴型、贴心姐妹',
    description: '陪伴型、贴心姐妹',
  },
  {
    id: 'Chinese (Mandarin)_Male_Announcer',
    label: '播报男声',
    lang: 'zh',
    gender: 'male',
    ageTag: 'adult',
    mood: '标准新闻播报',
    description: '标准新闻播报',
  },
  {
    id: 'Chinese (Mandarin)_Sweet_Lady',
    label: '甜美女声',
    lang: 'zh',
    gender: 'female',
    ageTag: 'adult',
    mood: '柔美清新',
    description: '柔美清新',
  },
  {
    id: 'Chinese (Mandarin)_Southern_Young_Man',
    label: '南方小哥',
    lang: 'zh',
    gender: 'male',
    ageTag: 'youth',
    mood: '南方口音、阳光男生',
    description: '南方口音、阳光男生',
  },
  {
    id: 'Chinese (Mandarin)_Wise_Women',
    label: '阅历姐姐',
    lang: 'zh',
    gender: 'female',
    ageTag: 'middle',
    mood: '成熟睿智、有故事感',
    description: '成熟睿智、有故事感',
  },
  {
    id: 'Chinese (Mandarin)_Gentle_Youth',
    label: '温润青年',
    lang: 'zh',
    gender: 'male',
    ageTag: 'adult',
    mood: '文艺青年、温柔安静',
    description: '文艺青年、温柔安静',
  },
  {
    id: 'Chinese (Mandarin)_Warm_Girl',
    label: '温暖少女',
    lang: 'zh',
    gender: 'female',
    ageTag: 'youth',
    mood: '治愈系少女',
    description: '治愈系少女',
  },
  {
    id: 'Chinese (Mandarin)_Kind-hearted_Elder',
    label: '花甲奶奶',
    lang: 'zh',
    gender: 'female',
    ageTag: 'senior',
    mood: '慈祥长者、岁月感',
    description: '慈祥长者、岁月感',
  },
  {
    id: 'Chinese (Mandarin)_Cute_Spirit',
    label: '憨憨萌兽',
    lang: 'zh',
    gender: 'neutral',
    ageTag: 'neutral',
    mood: '蠢萌可爱、生物音',
    description: '蠢萌可爱、生物音',
  },
  {
    id: 'Chinese (Mandarin)_Radio_Host',
    label: '电台男主播',
    lang: 'zh',
    gender: 'male',
    ageTag: 'adult',
    mood: '深夜电台、磁性低嗓',
    description: '深夜电台、磁性低嗓',
  },
  {
    id: 'Chinese (Mandarin)_Lyrical_Voice',
    label: '抒情男声',
    lang: 'zh',
    gender: 'male',
    ageTag: 'adult',
    mood: '唱歌级、情感充沛',
    description: '唱歌级、情感充沛',
  },
  {
    id: 'Chinese (Mandarin)_Straightforward_Boy',
    label: '率真弟弟',
    lang: 'zh',
    gender: 'male',
    ageTag: 'youth',
    mood: '真实自然、少年感',
    description: '真实自然、少年感',
  },
  {
    id: 'Chinese (Mandarin)_Sincere_Adult',
    label: '真诚青年',
    lang: 'zh',
    gender: 'male',
    ageTag: 'adult',
    mood: '踏实可信、真诚表达',
    description: '踏实可信、真诚表达',
  },
  {
    id: 'Chinese (Mandarin)_Gentle_Senior',
    label: '温柔学姐',
    lang: 'zh',
    gender: 'female',
    ageTag: 'adult',
    mood: '温柔知性、治愈系',
    description: '温柔知性、治愈系',
  },
  {
    id: 'Chinese (Mandarin)_Stubborn_Friend',
    label: '嘴硬竹马',
    lang: 'zh',
    gender: 'male',
    ageTag: 'youth',
    mood: '傲娇但又关心你的青梅竹马',
    description: '傲娇但又关心你的青梅竹马',
  },
  {
    id: 'Chinese (Mandarin)_Crisp_Girl',
    label: '清脆少女',
    lang: 'zh',
    gender: 'female',
    ageTag: 'youth',
    mood: '声音清亮、有穿透力',
    description: '声音清亮、有穿透力',
  },
  {
    id: 'Chinese (Mandarin)_Pure-hearted_Boy',
    label: '清澈邻家弟弟',
    lang: 'zh',
    gender: 'male',
    ageTag: 'youth',
    mood: '清爽邻家男孩',
    description: '清爽邻家男孩',
  },
  {
    id: 'Chinese (Mandarin)_Soft_Girl',
    label: '柔和少女',
    lang: 'zh',
    gender: 'female',
    ageTag: 'youth',
    mood: '软糯柔和',
    description: '软糯柔和',
  },

  // =====================
  // 🇭🇰 粤语（6 个）
  // =====================
  {
    id: 'Cantonese_ProfessionalHost（F)',
    label: '专业女主持(粤语)',
    lang: 'yue',
    gender: 'female',
    ageTag: 'adult',
    mood: '港式主持、字正腔圆',
    description: '港式主持、字正腔圆',
  },
  {
    id: 'Cantonese_GentleLady',
    label: '温柔女声(粤语)',
    lang: 'yue',
    gender: 'female',
    ageTag: 'adult',
    mood: '温柔婉约',
    description: '温柔婉约',
  },
  {
    id: 'Cantonese_ProfessionalHost（M)',
    label: '专业男主持(粤语)',
    lang: 'yue',
    gender: 'male',
    ageTag: 'adult',
    mood: '沉稳大气',
    description: '沉稳大气',
  },
  {
    id: 'Cantonese_PlayfulMan',
    label: '活泼男声(粤语)',
    lang: 'yue',
    gender: 'male',
    ageTag: 'youth',
    mood: '阳光开朗',
    description: '阳光开朗',
  },
  {
    id: 'Cantonese_CuteGirl',
    label: '可爱女孩(粤语)',
    lang: 'yue',
    gender: 'female',
    ageTag: 'youth',
    mood: '软糯少女',
    description: '软糯少女',
  },
  {
    id: 'Cantonese_KindWoman',
    label: '善良女声(粤语)',
    lang: 'yue',
    gender: 'female',
    ageTag: 'adult',
    mood: '温和亲切',
    description: '温和亲切',
  },

  // =====================
  // 🇬🇧 英文（16 个）
  // =====================
  {
    id: 'English_Trustworthy_Man',
    label: 'Trustworthy Man',
    lang: 'en',
    gender: 'male',
    ageTag: 'adult',
    mood: '值得信赖、稳重可靠',
    description: '值得信赖、稳重可靠',
  },
  {
    id: 'English_Graceful_Lady',
    label: 'Graceful Lady',
    lang: 'en',
    gender: 'female',
    ageTag: 'adult',
    mood: '优雅端庄',
    description: '优雅端庄',
  },
  {
    id: 'English_Aussie_Bloke',
    label: 'Aussie Bloke',
    lang: 'en',
    gender: 'male',
    ageTag: 'adult',
    mood: '澳洲哥们儿、口音明显',
    description: '澳洲哥们儿、口音明显',
  },
  {
    id: 'English_Whispering_girl',
    label: 'Whispering Girl',
    lang: 'en',
    gender: 'female',
    ageTag: 'youth',
    mood: '耳语女孩、ASMR感',
    description: '耳语女孩、ASMR感',
  },
  {
    id: 'English_Diligent_Man',
    label: 'Diligent Man',
    lang: 'en',
    gender: 'male',
    ageTag: 'adult',
    mood: '勤奋踏实',
    description: '勤奋踏实',
  },
  {
    id: 'English_Gentle-voiced_man',
    label: 'Gentle-voiced Man',
    lang: 'en',
    gender: 'male',
    ageTag: 'adult',
    mood: '温柔低嗓',
    description: '温柔低嗓',
  },
  {
    id: 'Charming_Lady',
    label: 'Charming Lady',
    lang: 'en',
    gender: 'female',
    ageTag: 'adult',
    mood: '魅力女性',
    description: '魅力女性',
  },
  {
    id: 'Sweet_Girl',
    label: 'Sweet Girl',
    lang: 'en',
    gender: 'female',
    ageTag: 'youth',
    mood: '甜美少女',
    description: '甜美少女',
  },
  {
    id: 'Cute_Elf',
    label: 'Cute Elf',
    lang: 'en',
    gender: 'female',
    ageTag: 'youth',
    mood: '精灵可爱风',
    description: '精灵可爱风',
  },
  {
    id: 'Attractive_Girl',
    label: 'Attractive Girl',
    lang: 'en',
    gender: 'female',
    ageTag: 'adult',
    mood: '迷人女孩',
    description: '迷人女孩',
  },
  {
    id: 'Serene_Woman',
    label: 'Serene Woman',
    lang: 'en',
    gender: 'female',
    ageTag: 'adult',
    mood: '沉静女性',
    description: '沉静女性',
  },
  {
    id: 'Santa_Claus',
    label: 'Santa Claus',
    lang: 'en',
    gender: 'male',
    ageTag: 'senior',
    mood: '圣诞老人',
    description: '圣诞老人',
  },
  {
    id: 'Charming_Santa',
    label: 'Charming Santa',
    lang: 'en',
    gender: 'male',
    ageTag: 'senior',
    mood: '魅力圣诞老人',
    description: '魅力圣诞老人',
  },
  {
    id: 'Grinch',
    label: 'Grinch',
    lang: 'en',
    gender: 'neutral',
    ageTag: 'neutral',
    mood: '格林奇式怪咖',
    description: '格林奇式怪咖',
  },
  {
    id: 'Rudolph',
    label: 'Rudolph',
    lang: 'en',
    gender: 'male',
    ageTag: 'youth',
    mood: '驯鹿鲁道夫、活泼少年',
    description: '驯鹿鲁道夫（活泼少年）',
  },
  {
    id: 'Arnold',
    label: 'Arnold',
    lang: 'en',
    gender: 'male',
    ageTag: 'adult',
    mood: '硬汉阿诺风格',
    description: '硬汉阿诺风格',
  },
]

/** 默认旁白音色（必须在 MINIMAX_TTS_VOICES 中存在且已验证） */
export const MINIMAX_DEFAULT_VOICE_ID = 'male-qn-qingse'

/** 返回给 LLM 的音色选择提示文本 */
export function getMinimaxVoiceCatalogPrompt(): string {
  const lines = MINIMAX_TTS_VOICES.map((v) => {
    const genderText = v.gender === 'male' ? '男' : v.gender === 'female' ? '女' : '中性'
    const ageText =
      v.ageTag === 'child' ? '儿童' : v.ageTag === 'youth' ? '青年' : v.ageTag === 'middle' ? '中年' : v.ageTag === 'senior' ? '老年' : '成年'
    return `- ${v.id}（${v.label}）：${v.description} / 性别：${genderText} / 年龄：${ageText} / 情绪：${v.mood}`
  })
  return lines.join('\n')
}

/** 根据 ID 查找音色选项 */
export function findVoiceById(id?: string | null): MinimaxVoiceOption | undefined {
  return MINIMAX_TTS_VOICES.find((v) => v.id === id)
}

/** 判断是否为已验证的 MiniMax 音色 */
export function isValidMinimaxVoiceId(id?: string | null): boolean {
  return !!id && MINIMAX_TTS_VOICES.some((v) => v.id === id)
}
